let similarword = [
    [{"word":"贈り物", "meaning":"not yet", "Eg":[""]}],
    [{"word":"増える", "meaning":"not yet", "Eg":[""]}],
    [{"word":"憎む", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    [{"word":"驚く", "meaning":"not yet", "Eg":[""]}],
    [{"word":"警察官", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    [{"word":"応募", "meaning":"not yet", "Eg":[""]}],
    [{"word":"(応援)", "meaning":"not yet", "Eg":[""]}],
    [{"word":"暮らす", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    [{"word":"経営", "meaning":"not yet", "Eg":[""]}],
    [{"word":"営業", "meaning":"not yet", "Eg":[""]}],
    [{"word":"労働者", "meaning":"not yet", "Eg":[""]}],
    [{"word":"苦労", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    [{"word":"消防士", "meaning":"not yet", "Eg":[""]}],
    [{"word":"防ぐ", "meaning":"not yet", "Eg":[""]}],
    [{"word":"訪日", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    [{"word":"消す", "meaning":"not yet", "Eg":[""]}],
    [{"word":"削除", "meaning":"not yet", "Eg":[""], "space":"little needed"}],
    [{"word":"危険", "meaning":"not yet", "Eg":[""]}],
    [{"word":"経験", "meaning":"not yet", "Eg":[""], "space":"little needed"}],
    [{"word":"経済", "meaning":"not yet", "Eg":[""]}],
    [{"word":"経験", "meaning":"not yet", "Eg":[""]}],
    [{"word":"怪しい", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    [{"word":"屋上", "meaning":"not yet", "Eg":[""]}],
    [{"word":"握手", "meaning":"not yet", "Eg":[""], "space":"needed"}],
    // [{"word":"危険", "meaning":"not yet", "Eg":[""]}],
]